LANDTILE EQU  0
WALLTILE EQU  1
WATRTILE EQU 15

TALK     EQU  1 << 4

const_value SET 1
	const TILESET_PLAYER_HOUSE ;01
	const TILESET_GLINT	;02
	const TILESET_HOUSE_1	;03
	const TILESET_HOUSE_2	;04
	const TILESET_CENTER	;05
	const TILESET_CAFE	;06
	const TILESET_LIGHTHOUSE	;07
	const TILESET_GATE	;08
	const TILESET_SCHOOL	;09
	const TILESET_CAVE	;10
	const TILESET_GROVE	;11
	const TILESET_MOUNTAIN	;12
	const TILESET_JUNGLE	;13
	const TILESET_SPOOKY	;14
	const TILESET_HAUNTED	;15
	const TILESET_RANCH	;16
	const TILESET_MART	;17
	const TILESET_PLAYER_ROOM	;18
	const TILESET_LAVA_CAVE	;19
	const TILESET_STARGLOW_CAVERN	;20
	const TILESET_HAUNTED_TV	;21
	const TILESET_LIBRARY	;22
	const TILESET_LUSTER	;23
	const TILESET_SNOW		;24
	const TILESET_PARK		;25

	const_def
	const PAL_BG_GRAY
	const PAL_BG_RED
	const PAL_BG_GREEN
	const PAL_BG_WATER
	const PAL_BG_YELLOW
	const PAL_BG_BROWN
	const PAL_BG_ROOF
	const PAL_BG_TEXT
