AnimationExtraPointers:
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw VenusaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharizardAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw BlastoiseAnimationExtra
	dw PikipekAnimationExtra
	dw TrumbeakAnimationExtra
	dw ToucannonAnimationExtra
	dw WeedleAnimationExtra
	dw KakunaAnimationExtra
	dw BeedrillAnimationExtra
	dw PidgeyAnimationExtra
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw RattataAnimationExtra
	dw RaticateAnimationExtra
	dw SpearowAnimationExtra
	dw FearowAnimationExtra
	dw EkansAnimationExtra
	dw ArbokAnimationExtra
	dw PikachuAnimationExtra
	dw RaichuAnimationExtra
	dw SandshrewAnimationExtra
	dw SandslashAnimationExtra
	dw NidoranFAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidoranMAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw BuizelAnimationExtra
	dw FloatzelAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw OddishAnimationExtra
	dw GloomAnimationExtra
	dw VileplumeAnimationExtra
	dw DwebbleAnimationExtra
	dw CrustleAnimationExtra
	dw VenonatAnimationExtra
	dw VenomothAnimationExtra
	dw DiglettAnimationExtra
	dw DugtrioAnimationExtra
	dw MeowthAnimationExtra
	dw PersianAnimationExtra
	dw PsyduckAnimationExtra
	dw GolduckAnimationExtra
	dw MankeyAnimationExtra
	dw PrimeapeAnimationExtra
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw AbraAnimationExtra
	dw KadabraAnimationExtra
	dw AlakazamAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw BellsproutAnimationExtra
	dw WeepinbellAnimationExtra
	dw VictreebelAnimationExtra
	dw TentacoolAnimationExtra
	dw TentacruelAnimationExtra
	dw GeodudeAnimationExtra
	dw GravelerAnimationExtra
	dw GolemAnimationExtra
	dw PonytaAnimationExtra
	dw RapidashAnimationExtra
	dw SlowpokeAnimationExtra
	dw SlowbroAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw FarfetchDAnimationExtra
	dw DoduoAnimationExtra
	dw DodrioAnimationExtra
	dw ShroomishAnimationExtra
	dw BreloomAnimationExtra
	dw GrimerAnimationExtra
	dw MukAnimationExtra
	dw ShellderAnimationExtra
	dw CloysterAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw MedititeAnimationExtra
	dw MedichamAnimationExtra
	dw CorphishAnimationExtra
	dw CrawdauntAnimationExtra
	dw VoltorbAnimationExtra
	dw ElectrodeAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorAnimationExtra
	dw CuboneAnimationExtra
	dw MarowakAnimationExtra
	dw BunearyAnimationExtra
	dw LopunnyAnimationExtra
	dw LickitungAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingAnimationExtra
	dw RhyhornAnimationExtra
	dw RhydonAnimationExtra
	dw NumelAnimationExtra
	dw TangelaAnimationExtra
	dw KangaskhanAnimationExtra
	dw HorseaAnimationExtra
	dw SeadraAnimationExtra
	dw GoldeenAnimationExtra
	dw SeakingAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw HawluchaAnimationExtra
	dw ScytherAnimationExtra
	dw VolcaronaAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw PinsirAnimationExtra
	dw TaurosAnimationExtra
	dw MagikarpAnimationExtra
	dw GyaradosAnimationExtra
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw PorygonAnimationExtra
	dw CottoneeAnimationExtra
	dw WhimsicottAnimationExtra
	dw KabutoAnimationExtra
	dw KabutopsAnimationExtra
	dw AerodactylAnimationExtra
	dw SnorlaxAnimationExtra
	dw ArticunoAnimationExtra
	dw ZapdosAnimationExtra
	dw MoltresAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw MewtwoAnimationExtra
	dw MewAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw SentretAnimationExtra
	dw FurretAnimationExtra
	dw NoibatAnimationExtra
	dw NoivernAnimationExtra
	dw LedybaAnimationExtra
	dw LedianAnimationExtra
	dw JoltikAnimationExtra
	dw GalvantulaAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw PichuAnimationExtra
	dw CleffaAnimationExtra
	dw IgglybuffAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw BellossomAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw AronAnimationExtra
	dw LaironAnimationExtra
	dw AggronAnimationExtra
	dw AipomAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw YanmaAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw SlowkingAnimationExtra
	dw MisdreavusAnimationExtra
	dw UnownAnimationExtra
	dw WobbuffetAnimationExtra
	dw GirafarigAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw QwilfishAnimationExtra
	dw ScizorAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw CorsolaAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw TogekissAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw KingdraAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw Porygon2AnimationExtra
	dw StantlerAnimationExtra
	dw SmeargleAnimationExtra
	dw SwabluAnimationExtra
	dw AltariaAnimationExtra
	dw LarvestaAnimationExtra
	dw ElekidAnimationExtra
	dw MagbyAnimationExtra
	dw MiltankAnimationExtra
	dw CameruptAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LugiaAnimationExtra
	dw RaichuAAnimationExtra
	dw Marowak_AAnimationExtra
