MapGroupPointers::
; pointers to the first map header of each map group
	dw MapGroup1
	dw MapGroup2
	dw MapGroup3
	dw MapGroup4
	dw MapGroup5
	dw MapGroup6
	dw MapGroup7
	dw MapGroup8
	dw MapGroup9
	dw MapGroup10
	dw MapGroup11
	dw MapGroup12
	dw MapGroup13
	dw MapGroup14
	dw MapGroup15
	dw MapGroup16
	dw MapGroup17
	dw MapGroup18
	dw MapGroup19
	dw MapGroup20
	dw MapGroup21
	dw MapGroup22
	dw MapGroup23
	dw MapGroup24
	dw MapGroup25
	dw MapGroup26
	dw MapGroup27


MapGroup1:
	map_header SunsetPokeCenter1F, TILESET_CENTER, INDOOR, SUNSET_BAY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivineGym, TILESET_PLAYER_HOUSE, INDOOR, SUNSET_BAY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SunsetGrassWaterHouse, TILESET_HOUSE_1, INDOOR, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SunsetCaptainsHouse, TILESET_HOUSE_2, INDOOR, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SunsetOldCoupleHouse, TILESET_HOUSE_1, INDOOR, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SunsetLegendsHouse, TILESET_HOUSE_1, INDOOR, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SunsetCafe, TILESET_CAFE, INDOOR, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivineMart, TILESET_PLAYER_HOUSE, INDOOR, SUNSET_BAY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route38EcruteakGate, TILESET_PLAYER_HOUSE, GATE, OCEAN, MUSIC_ROUTE_37, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route39Farmhouse, TILESET_PLAYER_HOUSE, ROUTE, OCEAN, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_NONE




MapGroup2:
	map_header MahoganyRedGyaradosSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, MAHOGANY_TOWN, MUSIC_SUNBEAM_ISLAND, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MahoganyGym, TILESET_PLAYER_HOUSE, INDOOR, MAHOGANY_TOWN, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MahoganyPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, MAHOGANY_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route42EcruteakGate, TILESET_PLAYER_HOUSE, GATE, ROUTE_42, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MahoganyTown, TILESET_PLAYER_HOUSE, TOWN, MAHOGANY_TOWN, MUSIC_SUNBEAM_ISLAND, 0, PALETTE_AUTO, FISHGROUP_NONE


MapGroup3:
	map_header SproutTower1F, TILESET_PLAYER_HOUSE, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SproutTower2F, TILESET_PLAYER_HOUSE, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SproutTower3F, TILESET_PLAYER_HOUSE, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower1F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower2F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower3F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower4F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower5F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower6F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower7F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower8F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTower9F, TILESET_PLAYER_HOUSE, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BurnedTower1F, TILESET_PLAYER_HOUSE, DUNGEON, BURNED_TOWER, MUSIC_BURNED_TOWER, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header BurnedTowerB1F, TILESET_PLAYER_HOUSE, CAVE, BURNED_TOWER, MUSIC_BURNED_TOWER, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RadioTower3F, TILESET_PLAYER_HOUSE, INDOOR, RADIO_TOWER, 1<<7 | MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RadioTower4F, TILESET_PLAYER_HOUSE, INDOOR, RADIO_TOWER, 1<<7 | MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RadioTower5F, TILESET_PLAYER_HOUSE, INDOOR, RADIO_TOWER, 1<<7 | MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RuinsofAlphOutside, TILESET_PLAYER_HOUSE, ROUTE, RUINS_OF_ALPH, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SunsetCapeRoute1Gate, TILESET_GATE, GATE, SUNSET_CAPE, MUSIC_ROUTE_1_NEW, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RuinsofAlphInnerChamber, TILESET_PLAYER_HOUSE, DUNGEON, RUINS_OF_ALPH, MUSIC_RUINS_OF_ALPH_INTERIOR, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RuinsofAlphResearchCenter, TILESET_PLAYER_HOUSE, INDOOR, RUINS_OF_ALPH, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header RuinsofAlphKabutoItemRoom, TILESET_PLAYER_HOUSE, DUNGEON, RUINS_OF_ALPH, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RuinsofAlphHoOhWordRoom, TILESET_PLAYER_HOUSE, DUNGEON, RUINS_OF_ALPH, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RuinsofAlphKabutoWordRoom, TILESET_PLAYER_HOUSE, DUNGEON, RUINS_OF_ALPH, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SlowpokeWellB1F, TILESET_PLAYER_HOUSE, CAVE, SLOWPOKE_WELL, MUSIC_LAVA, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SlowpokeWellB2F, TILESET_PLAYER_HOUSE, CAVE, SLOWPOKE_WELL, MUSIC_LAVA, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MahoganyMart1F, TILESET_PLAYER_HOUSE, INDOOR, MAHOGANY_TOWN, MUSIC_MAHOGANY_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TeamRocketBaseB1F, TILESET_PLAYER_HOUSE, DUNGEON, MAHOGANY_TOWN, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TeamRocketBaseB2F, TILESET_PLAYER_HOUSE, DUNGEON, MAHOGANY_TOWN, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TeamRocketBaseB3F, TILESET_PLAYER_HOUSE, DUNGEON, MAHOGANY_TOWN, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header IlexForest, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header WarehouseEntrance, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest1, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest2, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest3, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest4, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest5, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest6, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest7, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest8, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header SpookyForest9, TILESET_SPOOKY, DARK_FOREST, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header UndergroundPathSwitchRoomEntrances, TILESET_SPOOKY, DUNGEON, ILEX_FOREST, MUSIC_SPOOKY, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header GoldenrodDeptStoreB1F, TILESET_PLAYER_HOUSE, DUNGEON, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header UndergroundWarehouse, TILESET_PLAYER_HOUSE, DUNGEON, GOLDENROD_CITY, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MountMortar1FOutside, TILESET_PLAYER_HOUSE, CAVE, MT_MORTAR, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MountMortar1FInside, TILESET_PLAYER_HOUSE, CAVE, MT_MORTAR, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MountMortar2FInside, TILESET_PLAYER_HOUSE, CAVE, MT_MORTAR, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MountMortarB1F, TILESET_PLAYER_HOUSE, CAVE, MT_MORTAR, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header IcePath1F, TILESET_PLAYER_HOUSE, CAVE, ICE_PATH, MUSIC_LAVA, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header IcePathB1F, TILESET_PLAYER_HOUSE, CAVE, ICE_PATH, MUSIC_LAVA, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header IcePathB2FMahoganySide, TILESET_PLAYER_HOUSE, CAVE, ICE_PATH, MUSIC_LAVA, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header IcePathB2FBlackthornSide, TILESET_PLAYER_HOUSE, CAVE, ICE_PATH, MUSIC_LAVA, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header IcePathB3F, TILESET_PLAYER_HOUSE, CAVE, ICE_PATH, MUSIC_LAVA, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header WhirlIslandNW, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header WhirlIslandNE, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header WhirlIslandSW, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header WhirlIslandCave, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header WhirlIslandSE, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header WhirlIslandB1F, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header WhirlIslandB2F, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header WhirlIslandLugiaChamber, TILESET_PLAYER_HOUSE, CAVE, WHIRL_ISLANDS, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header SilverCaveRoom1, TILESET_PLAYER_HOUSE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header SilverCaveRoom2, TILESET_PLAYER_HOUSE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SilverCaveRoom3, TILESET_PLAYER_HOUSE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SilverCaveItemRooms, TILESET_PLAYER_HOUSE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header DarkCaveVioletEntrance, TILESET_PLAYER_HOUSE, CAVE, DARK_CAVE, MUSIC_LAVA, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header DarkCaveBlackthornEntrance, TILESET_PLAYER_HOUSE, CAVE, DARK_CAVE, MUSIC_LAVA, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header DragonsDen1F, TILESET_PLAYER_HOUSE, CAVE, DRAGONS_DEN, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header DragonsDenB1F, TILESET_PLAYER_HOUSE, CAVE, DRAGONS_DEN, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header DiglettsCave, TILESET_PLAYER_HOUSE, CAVE, DIGLETTS_CAVE, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MountMoon, TILESET_PLAYER_HOUSE, CAVE, MT_MOON, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SunsetLighthouse, TILESET_LIGHTHOUSE, GATE, LIGHTHOUSE, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header RockTunnel1F, TILESET_PLAYER_HOUSE, CAVE, ROCK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header RockTunnelB1F, TILESET_PLAYER_HOUSE, CAVE, ROCK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header SafariZoneFuchsiaGateBeta, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SafariZoneBeta, TILESET_PLAYER_HOUSE, CAVE, FUCHSIA_CITY, MUSIC_EVOLUTION, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header VictoryRoad, TILESET_PLAYER_HOUSE, CAVE, VICTORY_ROAD, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_NONE


MapGroup4:
	map_header EcruteakHouse, TILESET_PLAYER_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header WiseTriosRoom, TILESET_PLAYER_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header EcruteakPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header EcruteakLugiaSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header EcruteakMart, TILESET_PLAYER_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header EcruteakGym, TILESET_PLAYER_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header EcruteakItemfinderHouse, TILESET_PLAYER_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header EcruteakCity, TILESET_PLAYER_HOUSE, TOWN, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SunsetBay, TILESET_GLINT, TOWN, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_AUTO, FISHGROUP_SUNSET
	map_header SunsetCape, TILESET_GLINT, ROUTE, SUNSET_CAPE, MUSIC_SUNSET_BAY, 0, PALETTE_AUTO, FISHGROUP_SUNSET
	map_header Ocean1, TILESET_GLINT, ROUTE, OCEAN, MUSIC_ROUTE_2_NEW, 0, PALETTE_AUTO, FISHGROUP_SUNSET
	map_header Ocean2, TILESET_GLINT, ROUTE, OCEAN, MUSIC_ROUTE_2_NEW, 0, PALETTE_AUTO, FISHGROUP_SUNSET

MapGroup5:
	map_header BlackthornGym1F, TILESET_PLAYER_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BlackthornGym2F, TILESET_PLAYER_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BlackthornDragonSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BlackthornEmysHouse, TILESET_PLAYER_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BlackthornMart, TILESET_PLAYER_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BlackthornPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MoveDeletersHouse, TILESET_PLAYER_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BlackthornCity, TILESET_PLAYER_HOUSE, TOWN, BLACKTHORN_CITY, MUSIC_STARGLOW_VALLEY, 0, PALETTE_AUTO, FISHGROUP_NONE


MapGroup6:
	map_header CinnabarPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, CINNABAR_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CinnabarPokeCenter2FBeta, TILESET_CENTER, INDOOR, ROUTE_30, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route19FuchsiaGate, TILESET_CAVE, CAVE, SPROUT_TOWER, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header Route19, TILESET_MOUNTAIN, ROUTE, SPROUT_TOWER, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route20, TILESET_CAVE, CAVE, SPROUT_TOWER, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header Route21, TILESET_CAVE, CAVE, DAYBREAK_GROTTO, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header Route46, TILESET_LAVA_CAVE, CAVE, SPROUT_TOWER, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header Route44, TILESET_LAVA_CAVE, CAVE, SPROUT_TOWER, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header Route31, TILESET_LAVA_CAVE, CAVE, SPROUT_TOWER, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header CinnabarIsland, TILESET_PLAYER_HOUSE, TOWN, CINNABAR_ISLAND, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route35Goldenrodgate, TILESET_SCHOOL, INDOOR, ROUTE_30, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route36RuinsofAlphgate, TILESET_SCHOOL, INDOOR, ROUTE_30, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route35NationalParkgate, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_30, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route36NationalParkgate, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_30, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route30, TILESET_GLINT, ROUTE, ROUTE_30, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_LAKE


MapGroup7:
	map_header CeruleanGymBadgeSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeruleanPoliceStation, TILESET_PLAYER_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeruleanTradeSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeruleanPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeruleanPokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeruleanGym, TILESET_PLAYER_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CeruleanMart, TILESET_PLAYER_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route10PokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_10, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route10PokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_10, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PowerPlant, TILESET_PLAYER_HOUSE, INDOOR, POWER_PLANT, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route4, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_4, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route9, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_9, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route10North, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_10, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route24, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_24, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route25, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_25, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header CeruleanCity, TILESET_PLAYER_HOUSE, TOWN, CERULEAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header LakeofRage, TILESET_GLINT, TOWN, LAKE_OF_RAGE, MUSIC_STARGLOW, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header OlivineLighthouse1F, TILESET_HOUSE_1, INDOOR, LAKE_OF_RAGE, MUSIC_STARGLOW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivineLighthouse2F, TILESET_HOUSE_1, INDOOR, LAKE_OF_RAGE, MUSIC_STARGLOW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivineLighthouse3F, TILESET_HOUSE_1, INDOOR, LAKE_OF_RAGE, MUSIC_STARGLOW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivineLighthouse4F, TILESET_HOUSE_1, INDOOR, LAKE_OF_RAGE, MUSIC_STARGLOW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivineLighthouse5F, TILESET_CENTER, INDOOR, LAKE_OF_RAGE, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivineLighthouse6F, TILESET_MART, INDOOR, LAKE_OF_RAGE, MUSIC_STARGLOW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SeafoamGym, TILESET_HOUSE_2, INDOOR, LAKE_OF_RAGE, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route33, TILESET_GLINT, ROUTE, ROUTE_43, MUSIC_ROUTE_2_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route34, TILESET_GLINT, ROUTE, ROUTE_34, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header TohjoFalls, TILESET_GLINT, ROUTE, TOHJO_FALLS, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header Route42, TILESET_GLINT, ROUTE, ROUTE_42, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route40, TILESET_GLINT, ROUTE, ROUTE_42, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE


MapGroup8:
	map_header AzaleaPokeCenter1F, TILESET_CENTER, INDOOR, AZALEA_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CharcoalKiln, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_GLINT_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header AzaleaMart, TILESET_MART, INDOOR, AZALEA_TOWN, MUSIC_GLINT_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header KurtsHouse, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_GLINT_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BillsHouse, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_GLINT_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LakeofRageHiddenPowerHouse, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_GLINT_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header AzaleaGym, TILESET_LIBRARY, INDOOR, AZALEA_TOWN, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route45, TILESET_GLINT, ROUTE, ROUTE_45, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header DragonShrine, TILESET_GLINT, ROUTE, ROUTE_45, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route41, TILESET_GLINT, ROUTE, ROUTE_41, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header CherrygroveCity, TILESET_GLINT, TOWN, CHERRYGROVE_CITY, MUSIC_SUNBEAM_ISLAND, 0, PALETTE_AUTO, FISHGROUP_SUNBEAM
	map_header NationalPark, TILESET_GLINT, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header NationalParkBugContest, TILESET_GLINT, INDOOR, CHERRYGROVE_CITY, MUSIC_GAME_CORNER, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route29, TILESET_GLINT, TOWN, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_AUTO, FISHGROUP_SUNBEAM
	map_header Route27, TILESET_GLINT, INDOOR, CHERRYGROVE_CITY, MUSIC_GYM, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header CherrygroveMart, TILESET_MART, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CherrygrovePokeCenter1F, TILESET_CENTER, INDOOR, CHERRYGROVE_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CherrygroveGymSpeechHouse, TILESET_JUNGLE, INDOOR, CHERRYGROVE_CITY, MUSIC_GYM, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ElmsHouse, TILESET_PLAYER_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header KrissNeighborsHouse, TILESET_PLAYER_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GuideGentsHouse, TILESET_PLAYER_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CherrygroveEvolutionSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route30BerrySpeechHouse, TILESET_SCHOOL, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MrPokemonsHouse, TILESET_PLAYER_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VioletGym, TILESET_PLAYER_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_SUNBEAM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route43MahoganyGate, TILESET_GATE, GATE, ROUTE_42, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup9:
	map_header LakeofRageMagikarpHouse, TILESET_PLAYER_HOUSE, INDOOR, LAKE_OF_RAGE, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route43Gate, TILESET_CAVE, CAVE, DAYBREAK_GROTTO, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header Route43, TILESET_GLINT, ROUTE, ROUTE_43, MUSIC_ROUTE_2_NEW, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header AzaleaTown, TILESET_GLINT, TOWN, AZALEA_TOWN, MUSIC_GLINT_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route35, TILESET_GLINT, ROUTE, AZALEA_TOWN, MUSIC_GLINT_GROVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header UnionCave1F, TILESET_STARGLOW_CAVERN, CAVE, UNION_CAVE, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header UnionCaveB1F, TILESET_STARGLOW_CAVERN, CAVE, UNION_CAVE, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header UnionCaveB2F, TILESET_PLAYER_HOUSE, CAVE, UNION_CAVE, MUSIC_DAYBREAK_GROTTO, 1, PALETTE_NITE, FISHGROUP_NONE


MapGroup10:
	map_header Route36, TILESET_GLINT, ROUTE, ROUTE_36, MUSIC_ROUTE_2_NEW, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header Route37, TILESET_GLINT, ROUTE, ROUTE_37, MUSIC_ROUTE_1_NEW, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header VioletCity, TILESET_GLINT, TOWN, VIOLET_CITY, MUSIC_DAYBREAK_VILLAGE, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header VioletMart, TILESET_CAVE, CAVE, DAYBREAK_GROTTO, MUSIC_DAYBREAK_GROTTO, 0, PALETTE_NITE, FISHGROUP_CAVE
	map_header EarlsPokemonAcademy, TILESET_SCHOOL, INDOOR, VIOLET_CITY, MUSIC_DAYBREAK_VILLAGE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VioletNicknameSpeechHouse, TILESET_HOUSE_2, INDOOR, VIOLET_CITY, MUSIC_DAYBREAK_VILLAGE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VioletPokeCenter1F, TILESET_CENTER, INDOOR, VIOLET_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VioletOnixTradeHouse, TILESET_HOUSE_2, INDOOR, VIOLET_CITY, MUSIC_DAYBREAK_VILLAGE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route32PokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_32, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header RuinsofAlphOmanyteWordRoom, TILESET_HAUNTED, DUNGEON, RUINS_OF_ALPH, MUSIC_SPOOKY, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsofAlphOmanyteChamber, TILESET_HAUNTED, DUNGEON, RUINS_OF_ALPH, MUSIC_SPOOKY, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsofAlphOmanyteItemRoom, TILESET_HAUNTED, DUNGEON, RUINS_OF_ALPH, MUSIC_SPOOKY, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsofAlphAerodactylWordRoom, TILESET_HAUNTED, DUNGEON, RUINS_OF_ALPH, MUSIC_SPOOKY, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsofAlphAerodactylItemRoom, TILESET_HAUNTED, DUNGEON, RUINS_OF_ALPH, MUSIC_SPOOKY, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsofAlphAerodactylChamber, TILESET_HAUNTED, DUNGEON, RUINS_OF_ALPH, MUSIC_SPOOKY, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsofAlphKabutoChamber, TILESET_HAUNTED_TV, INDOOR, RUINS_OF_ALPH, MUSIC_SPOOKY, 1, PALETTE_NITE, FISHGROUP_NONE
	

MapGroup11:
	map_header GoldenrodCity, TILESET_LUSTER, TOWN, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RadioTower1F, TILESET_LUSTER, TOWN, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RadioTower2F, TILESET_LUSTER, TOWN, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header GoldenrodGym, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodBikeShop, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodHappinessRater, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodBillsHouse, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodMagnetTrainStation, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodFlowerShop, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodPPSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodNameRater, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStore1F, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStore2F, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStore3F, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStore4F, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStore5F, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStore6F, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStoreElevator, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodDeptStoreRoof, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodGameCorner, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GAME_CORNER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodPokeComCenter2FMobile, TILESET_PLAYER_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header IlexForestAzaleaGate, TILESET_GATE, GATE, ILEX_FOREST, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route34IlexForestGate, TILESET_GATE, GATE, ILEX_FOREST, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header DayCare, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_34, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup12:
	map_header Route6, TILESET_PARK, ROUTE, ROUTE_6, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route11, TILESET_RANCH, ROUTE, ROUTE_11, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RuinsofAlphHoOhItemRoom, TILESET_RANCH, ROUTE, ROUTE_11, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SilphCo1F, TILESET_HOUSE_2, INDOOR, ROUTE_11, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionHouseFishingSpeechHouse, TILESET_HOUSE_1, INDOOR, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionPokeCenter1F, TILESET_CENTER, INDOOR, VERMILION_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionPokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PokemonFanClub, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_11, MUSIC_ROUTE_4_NEW, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionMagnetTrainSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionMart, TILESET_MART, INDOOR, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionHouseDiglettsCaveSpeechHouse, TILESET_HOUSE_1, INDOOR, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionGym, TILESET_PLAYER_HOUSE, INDOOR, VERMILION_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route6SaffronGate, TILESET_GATE, GATE, SUNSET_CAPE, MUSIC_ROUTE_1_NEW, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route6UndergroundEntrance, TILESET_RANCH, INDOOR, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_NITE, FISHGROUP_NONE


MapGroup13:
	map_header VermilionCity, TILESET_RANCH, TOWN, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route1, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_1, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header PalletTown, TILESET_PLAYER_HOUSE, TOWN, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RedsHouse1F, TILESET_PLAYER_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header RedsHouse2F, TILESET_PLAYER_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BluesHouse, TILESET_PLAYER_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OaksLab, TILESET_PLAYER_HOUSE, INDOOR, PALLET_TOWN, MUSIC_POKEMON_TALK, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup14:
	map_header Route2, TILESET_SNOW, ROUTE, ROUTE_2, MUSIC_ROUTE_2, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header PewterCity, TILESET_SNOW, TOWN, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header PewterNidoranSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PewterGym, TILESET_PLAYER_HOUSE, INDOOR, PEWTER_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PewterMart, TILESET_PLAYER_HOUSE, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PewterPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, PEWTER_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PewterPokeCEnter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PewterSnoozeSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup15:
	map_header OlivinePort, TILESET_PLAYER_HOUSE, ROUTE, SUNSET_BAY, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header VermilionPort, TILESET_PLAYER_HOUSE, ROUTE, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header FastShip1F, TILESET_PLAYER_HOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header FastShipCabins_NNW_NNE_NE, TILESET_PLAYER_HOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header FastShipCabins_SW_SSW_NW, TILESET_PLAYER_HOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header FastShipCabins_SE_SSE_CaptainsCabin, TILESET_PLAYER_HOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header FastShipB1F, TILESET_PLAYER_HOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OlivinePortPassage, TILESET_PLAYER_HOUSE, INDOOR, SUNSET_BAY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VermilionPortPassage, TILESET_PLAYER_HOUSE, INDOOR, VERMILION_CITY, MUSIC_GLINT_GROVE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MountMoonSquare, TILESET_PLAYER_HOUSE, ROUTE, MT_MOON, MUSIC_MT_MOON_SQUARE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header MountMoonGiftShop, TILESET_PLAYER_HOUSE, INDOOR, MT_MOON, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TinTowerRoof, TILESET_PLAYER_HOUSE, ROUTE, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_AUTO, FISHGROUP_NONE


MapGroup16:
	map_header Route23, TILESET_PLAYER_HOUSE, TOWN, ROUTE_23, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header IndigoPlateauPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header WillsRoom, TILESET_PLAYER_HOUSE, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header KogasRoom, TILESET_PLAYER_HOUSE, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BrunosRoom, TILESET_PLAYER_HOUSE, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header KarensRoom, TILESET_PLAYER_HOUSE, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header LancesRoom, TILESET_PLAYER_HOUSE, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HallOfFame, TILESET_PLAYER_HOUSE, INDOOR, INDIGO_PLATEAU, MUSIC_NEW_BARK_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE


MapGroup17:
	map_header Route13, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_13, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route14, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_14, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route15, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_15, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route18, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_18, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header FuchsiaCity, TILESET_PLAYER_HOUSE, TOWN, FUCHSIA_CITY, MUSIC_CELADON_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header FuchsiaMart, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SafariZoneMainOffice, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header FuchsiaGym, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header FuchsiaBillSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header FuchsiaPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header FuchsiaPokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SafariZoneWardensHome, TILESET_PLAYER_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route15FuchsiaGate, TILESET_PLAYER_HOUSE, GATE, ROUTE_15, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup18:
	map_header Route8, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_8, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route12, TILESET_GLINT, ROUTE, ROUTE_12, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route10South, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_10, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header LavenderTown, TILESET_PLAYER_HOUSE, TOWN, LAVENDER_TOWN, MUSIC_LAVENDER_TOWN, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header LavenderPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LavenderPokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MrFujisHouse, TILESET_PLAYER_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LavenderTownSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LavenderNameRater, TILESET_PLAYER_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LavenderMart, TILESET_PLAYER_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SoulHouse, TILESET_PLAYER_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LavRadioTower1F, TILESET_PLAYER_HOUSE, INDOOR, LAV_RADIO_TOWER, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route8SaffronGate, TILESET_PLAYER_HOUSE, GATE, ROUTE_8, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route12SuperRodHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_12, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup19:
	map_header Route28, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_28, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SilverCaveOutside, TILESET_PLAYER_HOUSE, TOWN, SILVER_CAVE, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SilverCavePokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, SILVER_CAVE, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route28FamousSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_28, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup20:
	map_header PokeCenter2F, TILESET_PLAYER_HOUSE, INDOOR, SPECIAL_MAP, MUSIC_POKEMON_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TradeCenter, TILESET_PLAYER_HOUSE, INDOOR, SPECIAL_MAP, MUSIC_SUNBEAM_ISLAND, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Colosseum, TILESET_PLAYER_HOUSE, INDOOR, SPECIAL_MAP, MUSIC_SUNBEAM_ISLAND, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TimeCapsule, TILESET_PLAYER_HOUSE, INDOOR, SPECIAL_MAP, MUSIC_SUNBEAM_ISLAND, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MobileTradeRoomMobile, TILESET_PLAYER_HOUSE, INDOOR, SPECIAL_MAP, MUSIC_SUNBEAM_ISLAND, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MobileBattleRoom, TILESET_PLAYER_HOUSE, INDOOR, SPECIAL_MAP, MUSIC_SUNBEAM_ISLAND, 1, PALETTE_DAY, FISHGROUP_NONE


MapGroup21:
	map_header Route7, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_7, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route16, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route17, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_17, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header CeladonCity, TILESET_PLAYER_HOUSE, TOWN, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header CeladonDeptStore1F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonDeptStore2F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonDeptStore3F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonDeptStore4F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonDeptStore5F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonDeptStore6F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonDeptStoreElevator, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonMansion1F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonMansion2F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonMansion3F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonMansionRoof, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonMansionRoofHouse, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonPokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonGameCorner, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_GAME_CORNER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonGameCornerPrizeRoom, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonGym, TILESET_PLAYER_HOUSE, INDOOR, CELADON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonCafe, TILESET_HOUSE_1, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route16FuchsiaSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_16, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route16Gate, TILESET_PLAYER_HOUSE, GATE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route7SaffronGate, TILESET_PLAYER_HOUSE, GATE, ROUTE_7, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route1718Gate, TILESET_PLAYER_HOUSE, GATE, ROUTE_17, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup22:
	map_header CianwoodCity, TILESET_PLAYER_HOUSE, TOWN, CIANWOOD_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ManiasHouse, TILESET_PLAYER_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CianwoodGym, TILESET_PLAYER_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CianwoodPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CianwoodPharmacy, TILESET_PLAYER_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CianwoodCityPhotoStudio, TILESET_PLAYER_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CianwoodLugiaSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PokeSeersHouse, TILESET_PLAYER_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTower1F, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_GLINT_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTowerBattleRoom, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_GLINT_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTowerElevator, TILESET_PLAYER_HOUSE, INDOOR, BATTLE_TOWER, MUSIC_NONE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTowerHallway, TILESET_PLAYER_HOUSE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route40BattleTowerGate, TILESET_PLAYER_HOUSE, GATE, BATTLE_TOWER, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTowerOutside, TILESET_PLAYER_HOUSE, ROUTE, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 0, PALETTE_AUTO, FISHGROUP_NONE


MapGroup23:
	map_header Route3, TILESET_SNOW, ROUTE, ROUTE_3, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route22, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_22, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ViridianCity, TILESET_PLAYER_HOUSE, TOWN, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ViridianGym, TILESET_PLAYER_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header ViridianNicknameSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TrainerHouse1F, TILESET_PLAYER_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header TrainerHouseB1F, TILESET_PLAYER_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ViridianMart, TILESET_PLAYER_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ViridianPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ViridianPokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route2NuggetSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_2, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route2Gate, TILESET_PLAYER_HOUSE, GATE, ROUTE_2, MUSIC_ROUTE_2, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header VictoryRoadGate, TILESET_PLAYER_HOUSE, GATE, ROUTE_26, MUSIC_INDIGO_PLATEAU, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup24:
	map_header Route26, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_26, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header NewBarkTown, TILESET_PLAYER_HOUSE, TOWN, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ElmsLab, TILESET_SCHOOL, INDOOR, CHERRYGROVE_CITY, MUSIC_PROF_ELM, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header KrissHouse1F, TILESET_PLAYER_HOUSE, INDOOR, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header KrissHouse2F, TILESET_PLAYER_ROOM, INDOOR, SUNSET_BAY, MUSIC_SUNSET_BAY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route26HealSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_26, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route26DayofWeekSiblingsHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_26, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route27SandstormHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_27, MUSIC_STARGLOW_VALLEY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route2946Gate, TILESET_PLAYER_HOUSE, GATE, ROUTE_29, MUSIC_ROUTE_29, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup25:
	map_header Route5, TILESET_PLAYER_HOUSE, ROUTE, ROUTE_5, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SaffronCity, TILESET_PLAYER_HOUSE, TOWN, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header FightingDojo, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronGym, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronMart, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronPokeCenter1F, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronPokeCenter2FBeta, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header MrPsychicsHouse, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronTrainStation, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CopycatsHouse1F, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CopycatsHouse2F, TILESET_PLAYER_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route5UndergroundEntrance, TILESET_PLAYER_HOUSE, GATE, ROUTE_5, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route5SaffronCityGate, TILESET_PLAYER_HOUSE, GATE, ROUTE_5, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route5CleanseTagSpeechHouse, TILESET_PLAYER_HOUSE, INDOOR, ROUTE_5, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_NONE


MapGroup26:
	map_header Route31VioletGate, TILESET_PLAYER_HOUSE, GATE, ROUTE_31, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header DanceTheatre, TILESET_MOUNTAIN, ROUTE, SPROUT_TOWER, MUSIC_ROUTE_4_NEW, 0, PALETTE_AUTO, FISHGROUP_NONE
	
MapGroup27:
	map_header Route32, TILESET_GROVE, ROUTE, GLINT_GROVE, MUSIC_GLINT_GROVE, 0, PALETTE_AUTO, FISHGROUP_GLINT
	map_header Route32RuinsofAlphGate, TILESET_GROVE, ROUTE, GLINT_GROVE, MUSIC_GLINT_GROVE, 0, PALETTE_AUTO, FISHGROUP_NONE

